### PR TITLE
Hashcode and html generation

### PR DESCRIPTION
**Pull request by mhwasil**
using md5

### CODE REVIEW

**Comment by mhwasil** [comment]
* Cut hashcode to 20 char for sha1
* Make hashcode more readable by spliting it
* Add one txt file containing username, hashcode, timestamp (as backup in case students are not able to open html)
* Change to local timestamp (it's actually handled by nbgrader, no need to change setting in the pc config)
* Add option for hashcode generation (md5 and sha1)
* Update nbgrader with the current dev

**Comment by mhwasil** [comment]
* Add automatic hashcode_list.csv while collecting
* Add automatic html generation of all hashcode including username and timestamp
* Add hashed_submission for archieve
@deebuls

**Comment by mhwasil** [comment]
* Handle different name for asssignment_id and filename

**Comment by deebuls** [comment]
@wasil is this stable for merging ? or still we need development

**Comment by mhwasil** [comment]
@deebuls yeah, it's stable. The assumption in order for this to generate hashcode and list
* the notebook name should be the same as the assignment id
* If it's not the same, then it wont generate hashcode (i.e. for assignments)

**Pull request merged**
